shopapp.webui/Models/ProductDetailModel.cs
using System.Collections.Generic;
using shopapp.entity;

namespace shopapp.webui.Models
{
    public class ProductDetailModel
    {
        public Product Product { get; set; }
        public List<Category> Categories { get; set; }
    }
}

shopapp.webui/ViewModels/ProductViewModel.cs
using System.Collections.Generic;
using shopapp.entity;

public class ProductListViewModel
{
        public List<Product> Products { get; set; }
}

shopapp.webui/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.data.Abstract;

namespace shopapp.webui.Controllers
{
    public class HomeController : Controller
    {
        private IProductService _productService;
        public HomeController(IProductService productService )
        {
            this._productService=productService;
        }


        public IActionResult Index()
        {
            var productViewModel = new ProductListViewModel()
            {
                Products=_productService.GetAll()
            };

            return View(productViewModel);
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View("MyView");
        }
    }
}

shopapp.webui/Controllers/ShopController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class ShopController:Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService )
        {
            this._productService=productService;
        }

        public IActionResult List(string category, int page=1)
        {
            const int pageSize=3;
            var productViewModel = new ProductListViewModel()
            {
                Products=_productService.GetProductsByCategory(category,page,pageSize)
            };

            return View(productViewModel);
        }

        public IActionResult Details(string url)
        {
            if(url==null)
            {
                return NotFound();
            }
            
            Product product= _productService.GetProductDetails(url);

            if(product==null)
            {
                return NotFound();
            }
            return View(new ProductDetailModel{
                Product = product,
                Categories=product.ProductCategories.Select(i=>i.Category).ToList()
            });

        }
    }
}

shopapp.webui/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;

namespace shopapp.webui.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService )
        {
            this._categoryService=categoryService;
        }
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"]!=null)
                ViewBag.SelectedCategory=RouteData?.Values["category"];

            return View(_categoryService.GetAll());
        }
        
    }
}

shopapp.webui/Views/Home/About.cshtml
@section Categories
{
     @await Component.InvokeAsync("Categories")
}

about

shopapp.webui/Views/Home/Index.cshtml
@model ProductListViewModel

<partial name="_header">


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
            <div class="col-md-4">
                @await Html.PartialAsync("_product",product)
            </div>
            }
        </div>
    </div>
</div>


@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
}

shopapp.webui/Views/Home/MyView.cshtml
product/index

shopapp.webui/Views/Product/Create.cshtml
@model Product

<form method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl"  class="form-control">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>

    @*<div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control"> 
            <option selected disabled>Seçiniz</option>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
        </select>
    </div>*@

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

shopapp.webui/Views/Product/Edit.cshtml
@model Product

<form method="POST">
    
     <input type="hidden" name= "ProductId" value="@Model.ProductId"/>

    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
    </div>

    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
    </div>

    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
    </div>

    @*<div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control"> 
            <option selected disabled>Seçiniz</option>
        </select>
    </div>*@

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

shopapp.webui/Views/Product/Index.cshtml
@section Categories
{
     @await Component.InvokeAsync("Categories")
}

product/index

shopapp.webui/Views/Product/details.cshtml
@model Product
@section Categories
{
     @await Component.InvokeAsync("Categories")
}

<div class="card mb-3">
     <div class="card-body">
     <div class="row no-gutters">
          <div class="col-md-3">
               <img src="~/img/@Model.ImageUrl" class="card-img">
          </div>
          <div class="col md-9">
               <h5 class="card-title">@Model.Name</h5>
               <p class="card-text">@Model.Description</p>
               <p class="card-text">
                    <small class="text-muted">3 days ago<small>
               </p>
          </div>
     </div>
     </div>
</div>

shopapp.webui/Views/Product/list.cshtml
@model ProductListViewModel

@{
    var products = Model.Products;
}

@section Categories
{
     @await Component.InvokeAsync("Categories")
}


@if (products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">
        @foreach (var product in products)
        {
            <div class="col-md-4">
                @await Html.PartialAsync("_product",product)
            </div>
        }
    </div>
}        

shopapp.webui/Views/Shared/Components/Categories/Default.cshtml
@model List<Category>

<div class="list-group">
     
    <a href="/products" class="list-group-item list-group-item-action">Tüm Kategoriler</a>

    @foreach (var item in Model)
    {
    <a asp-controller="Shop" 
    asp-action="List" 
    asp-route-category="@item.Url" 
    class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == item.Url?"active":"")">
        @item.Name
    </a>
    }
</div> 

shopapp.webui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css">
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        crossorigin="anonymous"> -->
    <link rel="stylesheet" href="~/css/style.css">  
    <title>Shopapp</title>
</head>

<body>

    @await Html.PartialAsync("_navbar")

    <main class="mb-3">
        <div class="container">      
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
        </div>
    </main>

    <footer class="py-5 bg-dark text-white text-center">
        Shop App | 2020
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.js"crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/release/v5.8.1/css/all.css">

    @RenderSection("Scripts",false)

</body>

</html>

shopapp.webui/Views/Shared/_categories.cshtml
@model List<Category>

<div class="list-group">
    @foreach (var category in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@category.Name</a>
    }
</div>

shopapp.webui/Views/Shared/_header.cshtml
<header>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Shop App</h1>
            <p class="lead">Lorem ipsum dolor sit amet.</p>
        </div>
    </div>
</header>

shopapp.webui/Views/Shared/_navbar.cshtml
<div class="navbar bg-primary navbar-dark navbar-expand-sm">
    <div class="container">
        <a href="/" class="navbar-brand">Shopapp</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="/products" class="nav-link">Products</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Cart</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">Orders</a>
            </li>            
            <li class="nav-item">
                <a asp-controller="admin" asp-action="createproduct" class="nav-link">Add Product</a>
            </li>
            <li class="nav-item">
                <a asp-controller="admin" asp-action="productlist" class="nav-link">Admin Products</a>
            </li>
        </ul>

        <form action="/product/list" class="d-flex">
            <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light mr-2" type="submit">Search</button>
        </form>
    </div>
</div>

shopapp.webui/Views/Shared/_noproduct.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            Ürün Bulunamadı
        </div>
    </div>
</div>

shopapp.webui/Views/Shared/_product.cshtml
@model Product

<div class="card mb-2">
    <img class="card-img-top" src="~/img/@Model.ImageUrl" alt="">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <small class="text-muted">
            <i class="fas fa-lira-sign"></i>@Model.Price
        </small>
    </div>
    <div class="card-footer text-center">
        <a asp-controller="shop" asp-action="Details" asp-route-url="@Model.Url" class="btn btn-primary btn-sm">Details</a>
        <a asp-controller="shop" asp-action="addtocart" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">Add to Cart</a>
    </div>
</div>    

shopapp.webui/Views/Shop/Details.cshtml
@model ProductDetailModel

<div class="row">
     <div class="col-md-3">
          <img src="~/img/@Model.Product.ImageUrl" class="img-fluid">
     </div>
     <div class="col md-9">
          <h1 class="mb-3">@Model.Product.Name</h1> <hr>
          
          @foreach (var item in Model.Categories)
          {
          <a asp-controller="shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name </a> 
          }
          
          <div class="mb-3">
               <h4 class="text-primary mb-3">
                    <i class="fas fa-lira-sign"> </i>@Model.Product.Price 
               </h4>
          </div>
          <button type="submit" class="btn btn-primary btn-lg" >Add to Cart</button>
     </div>
</div>
<div class="row">
     <div class="col md-12">
          <p class="p-3">@Model.Product.Description</p>
     </div>
</div>

shopapp.webui/Views/Shop/List.cshtml
@model ProductListViewModel

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
            <div class="col-md-4">
                @await Html.PartialAsync("_product",product)
            </div>
            }
        </div>
    </div>
</div>

    
        

@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
}